name: 'Trello Changelog Builder'
description: 'A Github action that will allow you to build a changelog from a trello board.'
branding:
  color: red
inputs:
  apikey:
    description: 'The trello Api key needed to interact with trello'
    required: true
  apitoken:
    description: 'The trello Api token needed to interact with trello'
    required: true
  inputlist:
    description: 'The list to get the data for the changelog'
    required: true
  outputlist:
    description: 'The list to write the release data to.'
    required: false
  outputfile:
    description: 'The file to output the changelog to, default will be /github/workspace/changelog.md'
    required: false
    default: '/github/workspace/changelog.md'
  version:
    description: 'Allows you to manually specify a version, if left empty will bump +1 depending on releasetype'
    required: false
  versiontype:
    description: 'The type of release you want to bump, can be Major, Minor or Patch'
    required: false
  cleaninputs:
    description: 'Clean the input list from trello, deleting all of the cards'
    required: false
    default: false
  outputs:
    changelog:
      description: 'The formatted changelog in markdown'
    version:
      description: 'The version string'
    versionNumber:
      description: 'The Version in number format only'
  runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
    - '-k'
    - ${{ inputs.apikey }}
    - '-t'
    - ${{ inputs.apitoken }}
    - '-l'
    - ${{ inputs.inputlist }}
    - '-o'
    - ${{ inputs.outputlist }}
    - '-f'
    - ${{ inputs.outputfile }}
    - '-v'
    - ${{ inputs.version }}
    - '-g'
    - ${{ inputs.versiontype }}
    - '-c'
    - ${{ inputs.cleaninputs }}
